#!/bin/sh /etc/rc.common

START=19
STOP=10

SERVICE_DAEMONIZE=0
SERVICE_WRITE_PID=0

start()
{
	uci set dhcp.@dnsmasq[0].server=127.0.0.1#5353
	uci set dhcp.@dnsmasq[0].noresolv=1
}

stop()
{
	echo "Stop"
}
